name: backup-outline
on: [push] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.WIKI_REPO }}
          token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
          ref: master
          path: my-wiki

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: download backup
        run: |
          git clone https://github.com/3n3a/outline-backup
          cd outline-backup
          npm i
          node backup.js
          mv backup.zip ../my-wiki/docs
          cd ../my-wiki/docs
          unzip backup.zip
          rm backup.zip
        env:
          OUTLINE_URL: ${{ secrets.OUTLINE_URL }}
          OUTLINE_API_KEY: ${{ secrets.OUTLINE_API_KEY }}
          BACKUP_UA: ${{ secrets.BACKUP_UA }}
          
      - name: verify backup made changey
        run: |
          ls -lha 
          git status

      - name: Commit changes
        run: |
          cd my-wiki
          git add .
          git commit -m "add new backup from outline"
          git push
